apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xacmedatabases.acme.com
spec:
  group: acme.com
  names:
    kind: XAcmeDatabase
    plural: xacmedatabases
  claimNames:
    kind: AcmeDatabase
    plural: acmedatabases
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            description: "The OpenAPIV3Schema of this Composite Resource Definition."
            properties:
              userStr:
                type: string
                description: "A user provided string"
              storageGB:
                type: integer
                description: "The desired storage capacity of the database, in GB."
            required:
              - userStr
              - storageGB